import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Header from "@/components/Header"
import { getCurrentUser } from "@/lib/users/server"

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const currentUser = await getCurrentUser()

  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased bg-primary text-white`}>
        <Header initialUser={currentUser} />
        <main className="layout h-full pt-header">
          {children}
        </main>
      </body>
    </html>
  )
}
